import { Pill, Sparkles, Zap, Droplet, SprayCan, Wind, type LucideIcon } from "lucide-react";

export type CatalogCategory =
  | "Nutrilite"
  | "Artistry"
  | "XS"
  | "Personal Care"
  | "Home Care"
  | "Water & Air Treatment";

export type CatalogProduct = {
  slug: string;
  name: string;
  category: CatalogCategory;
  size: string;
  price: string;
  // confirmed = exact figure verified on an official listing
  // approx = a real figure found, but not independently corroborated: treat as estimate
  // on-request = no public figure exists; price varies / set by seller
  priceStatus: "confirmed" | "approx" | "on-request";
  ingredients: string[];
  description: string;
  hook: string;
  badge?: "Bestseller" | "New" | "Staff Pick";
  videoId?: string; // YouTube video ID for embed
  madeIn: string; // country of manufacture/origin
};

export const CATEGORY_INFO: Record<CatalogCategory, { blurb: string }> = {
  Nutrilite: {
    blurb: "The only global vitamin brand grown on its own certified organic farms.",
  },
  Artistry: {
    blurb: "Prestige-tier skincare and color cosmetics, sold exclusively through consultants.",
  },
  XS: {
    blurb: "Energy drinks built around a low-sugar, higher-caffeine formula.",
  },
  "Personal Care": {
    blurb: "Daily haircare, oral care, and body care built for repeat, everyday use.",
  },
  "Home Care": {
    blurb: "Concentrated formulas: a little goes a lot further than the bottle suggests.",
  },
  "Water & Air Treatment": {
    blurb: "Certified filtration systems, tested against 170+ contaminants.",
  },
};

type CategoryVisual = {
  icon: LucideIcon;
  gradient: string;
  // Real product photo, used in place of the icon mockup wherever set.
  image?: string;
  // "transparent": photo already has a cut-out/alpha background, drop straight on the page.
  // "card": photo has an opaque (usually white) background, so it needs a light plate behind it.
  photoStyle?: "transparent" | "card";
};

export const CATEGORY_VISUAL: Record<CatalogCategory, CategoryVisual> = {
  Nutrilite: { icon: Pill, gradient: "from-emerald-500/25 to-emerald-500/0" },
  Artistry: {
    icon: Sparkles,
    gradient: "from-rose-500/25 to-rose-500/0",
  },
  XS: {
    icon: Zap,
    gradient: "from-orange-500/25 to-orange-500/0",
  },
  "Personal Care": { icon: Droplet, gradient: "from-cyan-500/25 to-cyan-500/0" },
  "Home Care": { icon: SprayCan, gradient: "from-amber-500/25 to-amber-500/0" },
  "Water & Air Treatment": { icon: Wind, gradient: "from-blue-500/25 to-blue-500/0" },
};

// Placeholder stock photos until real product photography is in. Cycled
// across categories rather than one-per-category since there are only 4.
const PLACEHOLDER_PHOTOS = [
  "https://images.unsplash.com/photo-1494806812796-244fe51b774d?q=80&w=3534&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1518710843675-2540dd79065c?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1590041794748-2d8eb73a571c?q=80&w=3456&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1679420437432-80cfbf88986c?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
];

export const CATEGORY_PLACEHOLDER_IMAGE: Record<CatalogCategory, string> = {
  Nutrilite: PLACEHOLDER_PHOTOS[0],
  Artistry: PLACEHOLDER_PHOTOS[1],
  XS: PLACEHOLDER_PHOTOS[2],
  "Personal Care": PLACEHOLDER_PHOTOS[3],
  "Home Care": PLACEHOLDER_PHOTOS[0],
  "Water & Air Treatment": PLACEHOLDER_PHOTOS[1],
};

// Prices/ingredients researched from amway.com listings, FDA DailyMed (Glister),
// and EPA Safer Choice records where noted. amway.com blocks automated price
// scraping, so many figures are unconfirmed: priceStatus reflects that honestly.
export const catalog: CatalogProduct[] = [
  // ---------- Nutrilite ----------
  {
    slug: "nutrilite-double-x",
    name: "Nutrilite Double X Vitamin/Mineral/Phytonutrient Supplement",
    category: "Nutrilite",
    size: "31-day supply, with 3-compartment case",
    price: "$86.00",
    priceStatus: "confirmed",
    ingredients: [
      "Vitamin A (beta-carotene): supports vision, immune function, and skin health",
      "Vitamin C (ascorbic acid): supports immune function, collagen formation, and acts as an antioxidant",
      "Vitamin D3: supports bone health and calcium absorption",
      "Vitamin E (d-alpha-tocopheryl): antioxidant that protects cells from oxidative damage",
      "Thiamine / B1: supports energy metabolism and nerve function",
      "Riboflavin / B2: supports energy production and cellular function",
      "Niacin / B3: supports energy metabolism and healthy skin",
      "Vitamin B6: supports protein metabolism and brain function",
      "Folate: supports cell division and DNA synthesis",
      "Vitamin B12: supports nerve function and red blood cell formation",
      "Biotin: supports metabolism and healthy hair, skin, and nails",
      "Pantothenic acid / B5: supports energy metabolism from food",
      "Calcium (carbonate): supports bone and teeth strength",
      "Iron (fumarate): supports oxygen transport in the blood",
      "Iodine (potassium iodide, kelp): supports thyroid hormone production",
      "Magnesium (oxide): supports muscle, nerve, and bone function",
      "Zinc (oxide): supports immune function and wound healing",
      "Selenium (sodium selenite): antioxidant that supports thyroid function",
      "Copper (gluconate): supports iron metabolism and connective tissue",
      "Manganese (sulfate): supports bone formation and antioxidant enzymes",
      "Chromium (chloride): supports normal carbohydrate and fat metabolism",
      "Molybdenum (sodium molybdate): supports amino acid metabolism enzymes",
      "22 plant concentrates (lycopene, lutein, quercetin, rosemary and turmeric extracts, and more)",
      "Phytocolor Balance berry blend (grape, black currant, elderberry, blueberry)",
      "Phytoprotect Blend (rosemary, turmeric, fava d'anta extracts)",
    ],
    description: "Flagship daily multivitamin, mineral & phytonutrient supplement: 3 tablets, twice a day.",
    hook: "The best-known product in this lineup worldwide: grown on our own certified organic farms, not sourced from an anonymous supplement factory.",
    badge: "Bestseller",
    videoId: "bKagFfxwZtw",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-vitamin-c",
    name: "Nutrilite Vitamin C Extended Release",
    category: "Nutrilite",
    size: "60 tablets",
    price: "$28.00",
    priceStatus: "confirmed",
    ingredients: [
      "Vitamin C / ascorbic acid, 500 mg (556% DV): supports immune function, collagen formation, and acts as an antioxidant",
      "Acerola cherry powder, 120 mg: whole-food source contributing part of the vitamin C",
      "Citrus bioflavonoid complex, 35 mg: plant compound that naturally occurs alongside vitamin C in citrus",
      "Extended-release tablet matrix: releases over roughly 8 hours instead of all at once",
    ],
    description: "Slow-release vitamin C tablet for daily immune support.",
    hook: "Releases vitamin C over roughly 8 hours instead of spiking and clearing in one.",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-kids-chewable",
    name: "Nutrilite Kids Daily Chewable Multivitamins",
    category: "Nutrilite",
    size: "Chewable tablets, strawberry-orange",
    price: "$19.00",
    priceStatus: "confirmed",
    ingredients: [
      "Vitamin A: supports vision and immune function",
      "Vitamin C: supports immune function and acts as an antioxidant",
      "Vitamin D: supports bone health and calcium absorption",
      "Vitamin E: acts as an antioxidant",
      "Vitamin K: supports normal blood clotting and bone metabolism",
      "Thiamine / B1: supports energy metabolism",
      "Riboflavin / B2: supports energy production",
      "Niacin / B3: supports energy metabolism and healthy skin",
      "Vitamin B6: supports brain development and protein metabolism",
      "Folate: supports cell division and growth",
      "Vitamin B12: supports nerve function and red blood cell formation",
      "Biotin: supports metabolism and healthy hair and skin",
      "Pantothenic acid / B5: supports energy metabolism from food",
      "Calcium: supports bone and teeth development",
      "Iron: supports oxygen transport and cognitive development",
      "Iodine: supports thyroid hormone production",
      "Magnesium: supports muscle, nerve, and bone function",
      "Zinc: supports immune function and growth",
      "Nutrilite 5-Color Blend: pineapple, spinach, blueberry, passion fruit, papaya, and guava concentrates",
    ],
    description: "Chewable multivitamin formulated for children ages 4–12.",
    hook: "Tastes like fruit candy: the rare kids' vitamin nobody has to be bribed into taking.",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-omega",
    name: "Nutrilite Omega",
    category: "Nutrilite",
    size: "Softgel bottle",
    price: "$24.00",
    priceStatus: "confirmed",
    ingredients: [
      "Purified fish oil: anchovy, mackerel, sardine (Friend of the Sea certified sustainable)",
      "500+ mg combined EPA/DHA per serving",
      "White chia seed oil (ALA + natural vitamin E)",
    ],
    description: "Omega-3 fish oil softgel supplement for heart and brain health.",
    hook: "Certified sustainably wild-caught: not just a claim on the label, an actual third-party certification.",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-all-plant-protein",
    name: "Nutrilite All Plant Protein Powder",
    category: "Nutrilite",
    size: "Tri-blend powder",
    price: "$47.00",
    priceStatus: "confirmed",
    ingredients: [
      "Soy protein isolate (~80%)",
      "Wheat protein (~10%)",
      "Pea protein (~7.5%)",
      "8 g protein per 10 g serving: all 9 essential amino acids",
    ],
    description: "Plant-based protein powder built from a three-source blend.",
    hook: "A tri-blend engineered to cover all nine essential amino acids: something most single-source plant proteins can't say.",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-organics-plant-protein",
    name: "Nutrilite Organics Plant Protein Powder",
    category: "Nutrilite",
    size: "Vanilla or chocolate",
    price: "$41.00",
    priceStatus: "confirmed",
    ingredients: ["USDA-organic-certified plant protein blend", "No added sugar"],
    description: "USDA-organic-certified plant protein powder.",
    hook: "Nutrilite's newest protein line, and the first to carry full USDA Organic certification.",
    badge: "New",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-cal-mag-d",
    name: "Nutrilite Cal Mag D",
    category: "Nutrilite",
    size: "Tablet bottle",
    price: "$43.00",
    priceStatus: "confirmed",
    ingredients: [
      "Vitamin D3, 15 mcg (75% DV) per 3-tablet daily serving: supports bone health and calcium absorption",
      "Calcium (carbonate + calcified seaweed), 600 mg (46% DV): supports bone and teeth strength",
      "Magnesium (oxide), 200 mg (47% DV): supports muscle, nerve, and bone function",
      "Zinc (sulfate), 15 mg (136% DV): supports immune function and bone growth",
      "Manganese (citrate), 3.5 mg (152% DV): supports bone formation",
    ],
    description: "Bone-health supplement combining calcium, magnesium, vitamin D, zinc, and manganese.",
    hook: "Sources its calcium from calcified seaweed instead of ground-up rock.",
    madeIn: "USA",
  },

  // ---------- Artistry ----------
  {
    slug: "artistry-defying-serum",
    name: "Artistry Skin Nutrition Defying Serum",
    category: "Artistry",
    size: "30 mL / 1.0 fl. oz.",
    price: "$85.00",
    priceStatus: "confirmed",
    ingredients: [
      "Willow bark extract: gently smooths rough skin texture",
      "Hydrolyzed oats: calms and soothes irritated skin",
      "Ashwagandha root extract: an herb believed to help skin look firmer over time",
      "Seaweed extract: helps skin hold onto moisture",
      "Holy basil leaf extract: has calming, antioxidant properties",
      "Sodium hyaluronate: a lightweight moisture-holding ingredient (a form of hyaluronic acid)",
      "Chia seed extract: adds nourishing fatty acids that help skin stay soft",
    ],
    description: "Anti-aging facial serum targeting fine lines, pores, and skin elasticity.",
    hook: "Built around ashwagandha and holy basil extracts: ingredients most drugstore serums have never touched.",
    videoId: "wrCgBjvd5eU",
    madeIn: "USA",
  },
  {
    slug: "artistry-hydrating-gel-cream",
    name: "Artistry Skin Nutrition Hydrating Gel Cream",
    category: "Artistry",
    size: "50 mL / 1.7 fl. oz.",
    price: "$45.00",
    priceStatus: "confirmed",
    ingredients: [
      "\"Prevent Complex\": Artistry's own blend of plant ingredients meant to help skin stay hydrated through the day",
      "Bergamot, green tea, and amber: give the cream its light scent",
    ],
    description: "Daily gel-cream moisturizer for normal-to-oily skin.",
    hook: "A gel-cream light enough for oily skin, built on a proprietary botanical blend that isn't fully published.",
    madeIn: "USA",
  },
  {
    slug: "artistry-ideal-radiance-cc-cream",
    name: "Artistry Ideal Radiance Illuminating CC Cream",
    category: "Artistry",
    size: "30 mL / 1 fl. oz.",
    price: "$38.00",
    priceStatus: "confirmed",
    ingredients: [
      "AA2G (a stable form of vitamin C): helps brighten skin and fade uneven tone over time",
      "SPF 50: sunscreen protection built right into the cream",
    ],
    description: "Tinted CC cream with SPF 50 that evens tone and brightens skin.",
    hook: "SPF 50 and a stabilized vitamin-C derivative in one tinted cream: most CC creams only pick one.",
    madeIn: "USA",
  },
  {
    slug: "artistry-signature-eyes-mascara",
    name: "Artistry Signature Eyes Length & Definition Mascara (Black)",
    category: "Artistry",
    size: "8.3 mL / 0.28 fl. oz.",
    price: "$24.00",
    priceStatus: "confirmed",
    ingredients: ["Full ingredient list not independently published: ask for the current product insert"],
    description: "Volumizing, lengthening mascara in black.",
    hook: "Volumizing and lengthening in the same tube: no separate primer step required.",
    madeIn: "USA",
  },
  {
    slug: "artistry-go-vibrant-lipstick",
    name: "Artistry Go Vibrant Cream Lipstick",
    category: "Artistry",
    size: "0.13 oz",
    price: "$26.00",
    priceStatus: "confirmed",
    ingredients: [
      "Liquid-pigment color base: gives long-lasting color that feels lightweight instead of heavy or waxy",
      "Available in 10 shades",
    ],
    description: "Cream-finish lipstick available in 10 shades.",
    hook: "Uses a liquid-pigment base for color meant to feel weightless, not waxy.",
    badge: "New",
    madeIn: "USA",
  },
  {
    slug: "artistry-men-balancing-hydrator",
    name: "Artistry Men Balancing Hydrator",
    category: "Artistry",
    size: "150 mL",
    price: "$19.90",
    priceStatus: "confirmed",
    ingredients: [
      "Zinc PCA: helps control oil and shine through the day",
      "Witch hazel extract: a natural toner that helps tighten the look of pores",
      "Aloe leaf juice: soothes and hydrates skin",
      "Caffeine: helps de-puff and perk up tired-looking skin",
      "Sodium hyaluronate: helps skin hold onto moisture",
      "Ceramide 3: helps repair and strengthen skin's natural protective barrier",
    ],
    description: "Lightweight daily toner-moisturizer for men: oil control and hydration.",
    hook: "Built for men's skin specifically: oil control and hydration in one step, no separate toner needed.",
    madeIn: "USA",
  },
  {
    slug: "artistry-exact-fit-powder-foundation",
    name: "Artistry Exact Fit Powder Foundation",
    category: "Artistry",
    size: "12 g / 0.4 oz.",
    price: "$32.00",
    priceStatus: "confirmed",
    ingredients: [
      "Talc, kaolin, and pearl powder: mineral powders that create a smooth, blurred matte finish",
      "SPF 20: built-in sun protection so you can skip a separate sunscreen step",
    ],
    description: "Pressed powder foundation with SPF 20, oil-control matte finish.",
    hook: "Pressed powder with SPF 20 built in: skips the separate sunscreen step most powders require.",
    madeIn: "USA",
  },

  // ---------- Personal Care ----------
  {
    slug: "satinique-smooth-moisture-shampoo",
    name: "Satinique Smooth Moisture Shampoo",
    category: "Personal Care",
    size: "280 mL",
    price: "$15.00",
    priceStatus: "confirmed",
    ingredients: [
      "Almond oil: adds shine and softness to dry, unruly hair",
      "Sunflower seed complex water: helps lock in moisture",
    ],
    description: "Moisturizing shampoo for dry, unruly hair.",
    hook: "Built around a sunflower-seed water complex you won't find in a drugstore shampoo aisle.",
    videoId: "jB-GeJZ30EQ",
    madeIn: "USA",
  },
  {
    slug: "satinique-smooth-moisture-conditioner",
    name: "Satinique Smooth Moisture Conditioner",
    category: "Personal Care",
    size: "Companion size to the Smooth Moisture Shampoo",
    price: "$15.00",
    priceStatus: "confirmed",
    ingredients: [
      "Almond oil: adds shine and softness to dry, unruly hair",
      "Sunflower seed complex water: helps lock in moisture",
    ],
    description: "Moisturizing conditioner paired with the Smooth Moisture Shampoo.",
    hook: "Formulated as one half of a pair: not a generic conditioner bottled to match anything.",
    madeIn: "USA",
  },
  {
    slug: "glister-toothpaste",
    name: "Glister Multi-Action Fluoride Toothpaste",
    category: "Personal Care",
    size: "200 g",
    price: "$7.25",
    priceStatus: "confirmed",
    ingredients: [
      "Sodium fluoride 0.21%: the active ingredient that fights cavities",
      "Hydrated silica: a gentle polishing ingredient that helps remove surface stains",
      "Xylitol: a sugar substitute that also helps fight cavity-causing bacteria",
      "Sorbitol and glycerin: keep the paste smooth and moist",
    ],
    description: "Anticavity fluoride toothpaste that cleans, helps whiten, and freshens breath.",
    hook: "Its fluoride content is on file with the FDA's own public drug listing database: not just on the box.",
    videoId: "1yAZfkYcQpA",
    madeIn: "USA",
  },
  {
    slug: "glister-oral-rinse",
    name: "Glister Multi-Action Concentrated Oral Rinse",
    category: "Personal Care",
    size: "59 mL concentrate (~100 rinses)",
    price: "$14.00",
    priceStatus: "confirmed",
    ingredients: [
      "Cetylpyridinium chloride: the active ingredient that kills germs and helps reduce plaque",
      "Peppermint flavor: freshens breath, alcohol-free so it won't sting or burn",
    ],
    description: "Alcohol-free concentrated oral rinse that reduces plaque and freshens breath.",
    hook: "One small concentrate bottle stretches into about 100 rinses: no alcohol burn included.",
    madeIn: "USA",
  },
  {
    slug: "gh-protect-deodorant-roll-on",
    name: "g&h Protect Antiperspirant Deodorant Roll-On",
    category: "Personal Care",
    size: "100 mL",
    price: "$10.75",
    priceStatus: "confirmed",
    ingredients: [
      "Nutrilite-certified green tea extract: a natural antioxidant",
      "Cica water: a calming plant extract that soothes irritated skin",
      "Rosemary extract: adds antioxidant protection",
      "Prebiotics: help support the skin's healthy bacteria",
    ],
    description: "Roll-on antiperspirant/deodorant rated for up to 48-hour protection.",
    hook: "Uses the same Nutrilite-certified green tea extract as the supplement line: not an unrelated formula slapped on a new label.",
    madeIn: "USA",
  },
  {
    slug: "gh-protect-plus-deodorant",
    name: "G&H Protect+ Long Lasting Deodorant",
    category: "Personal Care",
    size: "83.6 g stick",
    price: "$10.50",
    priceStatus: "confirmed",
    ingredients: ["Aluminum-free, alcohol-free, paraben-free, plant-based formula"],
    description: "Aluminum-free deodorant stick for daily use, rated 24-hour+ protection.",
    hook: "Skips aluminum entirely without giving up all-day odor protection.",
    madeIn: "USA",
  },
  {
    slug: "gh-nourish-body-wash",
    name: "g&h Nourish Body Wash",
    category: "Personal Care",
    size: "400 mL",
    price: "$14.50",
    priceStatus: "confirmed",
    ingredients: [
      "Nutrilite white chia seed oil: nourishes and softens skin",
      "Bamboo water: helps hydrate skin",
      "Olive oil: moisturizes; the formula overall is sulfate-free (no harsh foaming agents)",
    ],
    description: "Moisturizing, sulfate-free body wash for dry skin.",
    hook: "Gentle enough to double as a face wash: most body washes won't make that claim.",
    madeIn: "USA",
  },

  // ---------- XS ----------
  {
    slug: "xs-classic",
    name: "XS Energy Drink: Classic",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "confirmed",
    ingredients: [
      "114 mg caffeine per can",
      "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy",
      "Panax and American ginseng: herbal extracts traditionally used for energy and focus",
      "Sugar-free: sweetened with sucralose & acesulfame potassium",
    ],
    description: "The original XS flavor: sugar-free, 15 calories per can.",
    hook: "114 mg of caffeine and zero sugar: built to hit without the crash that follows a sugary energy drink.",
    badge: "Bestseller",
    videoId: "MI0n6j8yCak",
    madeIn: "USA",
  },
  {
    slug: "xs-tropical",
    name: "XS Energy Drink: Tropical",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "confirmed",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Tropical fruit flavored energy drink, sugar-free, 15 calories per can.",
    hook: "Same energy formula as Classic, in a tropical-fruit flavor for people who find Classic too plain.",
    madeIn: "USA",
  },
  {
    slug: "xs-black-cherry-cola",
    name: "XS Energy Drink: Black Cherry Cola",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "confirmed",
    ingredients: ["114 mg caffeine per can", "Cherry juice concentrate", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy"],
    description: "Cherry-cola flavored energy drink, sugar-free, 15 calories per can.",
    hook: "Tastes like a cherry cola float: real cherry juice concentrate does the flavor work.",
    madeIn: "USA",
  },
  {
    slug: "xs-sparkling-dragon-fruit",
    name: "XS Sparkling Juiced Energy: Dragon Fruit",
    category: "XS",
    size: "12 fl oz can",
    price: "$37.00",
    priceStatus: "confirmed",
    ingredients: [
      "25% real fruit juice from concentrate",
      "~11 g sugar (naturally from juice, none added)",
      "280% DV vitamin C",
      "114 mg caffeine",
    ],
    description: "Juice-based sparkling energy drink made with real fruit juice.",
    hook: "280% of a day's vitamin C in one can: most energy drinks skip that entirely.",
    badge: "New",
    madeIn: "USA",
  },
  {
    slug: "xs-energy-burn-kiwi-strawberry",
    name: "XS Energy + Burn: Kiwi Strawberry",
    category: "XS",
    size: "12 fl oz can",
    price: "$42.00",
    priceStatus: "confirmed",
    ingredients: [
      "Green tea extract (~50 mg EGCG per can)",
      "114 mg caffeine",
      "Chromium, ginger root extract",
    ],
    description: "Metabolism-support energy drink line built around green tea extract.",
    hook: "Adds 50 mg of EGCG from green tea on top of the usual energy blend: a metabolism angle most energy drinks skip.",
    badge: "New",
    madeIn: "USA",
  },
  {
    slug: "xs-cranberry-grape",
    name: "XS Energy Drink: Cranberry-Grape",
    category: "XS",
    size: "12 fl oz can, case of 12 (caffeine-free version also available)",
    price: "$37.00",
    priceStatus: "confirmed",
    ingredients: ["114 mg caffeine per can", "Cranberry juice concentrate", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy"],
    description: "Cranberry-grape flavored energy drink, sugar-free, 15 calories per can.",
    hook: "The only flavor in the lineup that also comes in a caffeine-free version.",
    madeIn: "USA",
  },
  {
    slug: "xs-creatine-plus",
    name: "XS Creatine+",
    category: "XS",
    size: "30-serving tub, unflavored",
    price: "Ask for current price",
    priceStatus: "on-request",
    ingredients: [
      "Creatine monohydrate, 5 g: supports muscle strength, power output, and recovery between sets",
      "Calcium HMB, 2 g: may help offset exercise-induced muscle breakdown",
      "Electrolyte blend (sodium, potassium, magnesium): supports hydration during training",
    ],
    description: "Unflavored, unsweetened creatine monohydrate powder with added calcium HMB and electrolytes.",
    hook: "Third-party certified by Informed Choice, so what's tested on the label is what's actually in the tub.",
    badge: "New",
    madeIn: "Not publicly confirmed",
  },

  // ---------- Home Care ----------
  {
    slug: "sa8-powder-detergent",
    name: "SA8 Premium Powder Laundry Detergent",
    category: "Home Care",
    size: "3 kg (6.6 lbs)",
    price: "$53.00",
    priceStatus: "confirmed",
    ingredients: [
      "Sodium carbonate and cleaning agents: lift dirt and stains out of fabric",
      "Enzymes: break down food and grass stains at a molecular level",
      "Brightener: helps whites look whiter",
      "Low-suds, biodegradable, phosphate-free formula: safe in HE washers without needing special dosing",
    ],
    description: "Concentrated powder laundry detergent, Kosher certified and safe in all washers including HE machines.",
    hook: "Concentrated enough that a single scoop is designed to replace a full cup of typical store-brand powder.",
    videoId: "j9KIF5h8sts",
    madeIn: "USA",
  },
  {
    slug: "sa8-liquid-detergent",
    name: "SA8 Liquid Laundry Detergent",
    category: "Home Care",
    size: "4 L (135 fl oz)",
    price: "$53.00",
    priceStatus: "confirmed",
    ingredients: [
      "Concentrated cleaning agents that lift dirt and stains out of fabric",
      "Biodegradable, phosphate-free formula",
    ],
    description: "Concentrated liquid laundry detergent.",
    hook: "One 4-liter bottle is designed to outlast several jugs of a typical big-box detergent.",
    madeIn: "USA",
  },
  {
    slug: "loc-multi-purpose-cleaner",
    name: "L.O.C. Multi-Purpose Cleaner",
    category: "Home Care",
    size: "1 L concentrate: refills a 500 mL spray bottle up to 20 times",
    price: "$12.50",
    priceStatus: "confirmed",
    ingredients: [
      "Concentrated, biodegradable: no phosphates, chlorine, or harsh acids",
      "EPA Safer Choice recognized",
      "Dermatologist and allergy tested",
    ],
    description: "All-purpose concentrated household cleaner, safe on most surfaces.",
    hook: "One EPA Safer Choice-recognized bottle refills a spray bottle up to 20 times.",
    badge: "Bestseller",
    videoId: "IEawRZgO64k",
    madeIn: "USA",
  },
  {
    slug: "dish-drops",
    name: "Dish Drops Dishwashing Liquid",
    category: "Home Care",
    size: "1 L concentrate",
    price: "$16.00",
    priceStatus: "confirmed",
    ingredients: [
      "Aloe vera and shiso extract: plant ingredients that help keep hands from drying out while you wash dishes",
      "Biodegradable, no phosphates or chlorine",
    ],
    description: "Concentrated dishwashing liquid with aloe vera and shiso extract.",
    hook: "Rated to clean over 330 sinks full of dishes from a single bottle.",
    madeIn: "USA",
  },
  {
    slug: "kitchen-cleaner",
    name: "Kitchen Cleaner",
    category: "Home Care",
    size: "1 L refill",
    price: "$17.00",
    priceStatus: "confirmed",
    ingredients: [
      "EPA Safer Choice recognized",
      "Independently rated SkinSAFE 91% free of common allergens",
      "Talc-free, paraben-free",
    ],
    description: "Concentrated kitchen surface cleaner and degreaser.",
    hook: "Independently rated 91% free of the most common allergens: verified by a third party, not just a label claim.",
    madeIn: "USA",
  },
  {
    slug: "bathroom-cleaner",
    name: "Bathroom Cleaner",
    category: "Home Care",
    size: "1 L concentrate: refills a 500 mL spray bottle up to 8 times",
    price: "$17.00",
    priceStatus: "confirmed",
    ingredients: [
      "Citric acid: a natural ingredient that dissolves soap scum and hard-water buildup",
      "Biodegradable, no phosphates or chlorine",
    ],
    description: "Concentrated bathroom cleaner for soap scum and hard-water deposits.",
    hook: "Uses citric acid to dissolve hard-water scale instead of harsher acids under your sink.",
    madeIn: "USA",
  },
  {
    slug: "sa8-prewash-spray",
    name: "SA8 Prewash Spray",
    category: "Home Care",
    size: "Aerosol",
    price: "$18.50",
    priceStatus: "confirmed",
    ingredients: [
      "Concentrated cleaning agents: break down set-in stains before you wash",
      "Formulated safe for colorfast fabrics (won't fade colors)",
    ],
    description: "Aerosol laundry pre-treatment spray for stubborn, set-in stains.",
    hook: "Meant for the stains your regular detergent already gave up on.",
    madeIn: "USA",
  },

  // ---------- Water & Air Treatment ----------
  {
    slug: "espring-under-counter",
    name: "eSpring Under the Counter Water Treatment System",
    category: "Water & Air Treatment",
    size: "Under-counter install, single-line output",
    price: "$1,299.00",
    priceStatus: "confirmed",
    ingredients: [
      "Carbon block filter: traps contaminants and improves the taste and smell of your water",
      "UV-C light stage: kills bacteria and viruses without adding chemicals",
      "Reduces 170+ contaminants, including \"forever chemicals\" (PFOA/PFOS) and microplastics down to 0.2 microns",
      "Leaves in the beneficial minerals (calcium, magnesium) your water naturally has",
    ],
    description: "Full under-counter home water treatment and purification system.",
    hook: "Filters down to 0.2 microns while leaving the beneficial minerals in your water untouched.",
    badge: "Bestseller",
    videoId: "p5hZ4YAAU9M",
    madeIn: "USA",
  },
  {
    slug: "espring-e3-filter",
    name: "eSpring e3 Carbon Filter (replacement)",
    category: "Water & Air Treatment",
    size: "1 cartridge: rated ~1 year / 1,320 gallons",
    price: "$254.00",
    priceStatus: "confirmed",
    ingredients: [
      "Pre-filter layer: catches larger particles like sediment and rust",
      "Membrane layer: blocks smaller contaminants like lead and microplastics",
      "Carbon layer: removes chlorine taste and smell",
    ],
    description: "Annual replacement filter cartridge for current-generation eSpring systems.",
    hook: "One cartridge is rated for a full year or 1,320 gallons: whichever comes first.",
    madeIn: "USA",
  },
  {
    slug: "atmosphere-sky",
    name: "Atmosphere Sky Air Treatment System",
    category: "Water & Air Treatment",
    size: "Whole-room unit, WiFi/app enabled",
    price: "$1,710.00",
    priceStatus: "confirmed",
    ingredients: [
      "Washable pre-filter: catches larger particles like dust and pet hair, rinse and reuse it",
      "HEPA filter: traps fine particles like pollen and smoke",
      "Carbon filter: absorbs household odors",
      "Removes up to 99.99% of airborne particles as small as 0.0024 microns, per the manufacturer",
      "Covers rooms up to ~465 sq ft",
    ],
    description: "Smart whole-room air purifier system with app control.",
    hook: "Claims to catch particles as small as 0.0024 microns: smaller than most viruses.",
    videoId: "4kPqoatVQAc",
    badge: "New",
    madeIn: "USA",
  },
  {
    slug: "atmosphere-sky-hepa-filter",
    name: "Atmosphere Sky Replacement HEPA Filter",
    category: "Water & Air Treatment",
    size: "1 filter: rated 1–3 years",
    price: "$192.00",
    priceStatus: "confirmed",
    ingredients: ["HEPA filtration stage", "Removes airborne allergens, bacteria, mold, and viruses (manufacturer claim)"],
    description: "Replacement HEPA filter stage for the Atmosphere Sky system.",
    hook: "A single filter stage rated to last up to three years, depending on your air quality.",
    madeIn: "USA",
  },
  {
    slug: "atmosphere-sky-carbon-filter",
    name: "Atmosphere Sky Replacement Carbon (Odor) Filter",
    category: "Water & Air Treatment",
    size: "1 filter: rated 4–12 months",
    price: "$140.00",
    priceStatus: "confirmed",
    ingredients: ["Activated carbon filtration stage", "Targets household odors and gaseous contaminants"],
    description: "Replacement odor/carbon filter stage for the Atmosphere Sky system.",
    hook: "The stage that handles smell, not particles: swapped far more often than the HEPA filter.",
    madeIn: "USA",
  },
];
