import { Pill, Sparkles, Zap, Droplet, SprayCan, Wind, type LucideIcon } from "lucide-react";

export type CatalogCategory =
  | "Nutrilite"
  | "Artistry"
  | "XS"
  | "Personal Care"
  | "Home Care"
  | "Water & Air Treatment";

export type CatalogProduct = {
  slug: string;
  name: string;
  category: CatalogCategory;
  size: string;
  price: string;
  // confirmed = exact figure verified on an official listing
  // approx = a real figure found, but not independently corroborated: treat as estimate
  // on-request = no public figure exists; price varies / set by seller
  priceStatus: "confirmed" | "approx" | "on-request";
  ingredients: string[];
  description: string;
  hook: string;
  badge?: "Bestseller" | "New" | "Staff Pick";
  videoId?: string; // YouTube video ID for embed
  madeIn: string; // country of manufacture/origin
  // Real product photo for this specific item, overriding the category-level image.
  image?: string;
  // "transparent": photo already has a cut-out/alpha background, drop straight on the page.
  // "card": photo has an opaque (usually white) background, so it needs a light plate behind it.
  photoStyle?: "transparent" | "card";
};

export const CATEGORY_INFO: Record<CatalogCategory, { blurb: string }> = {
  Nutrilite: {
    blurb: "The only global vitamin brand grown on its own certified organic farms.",
  },
  Artistry: {
    blurb: "Prestige-tier skincare and color cosmetics, sold exclusively through consultants.",
  },
  XS: {
    blurb: "Energy drinks built around a low-sugar, higher-caffeine formula.",
  },
  "Personal Care": {
    blurb: "Daily haircare, oral care, and body care built for repeat, everyday use.",
  },
  "Home Care": {
    blurb: "Concentrated formulas: a little goes a lot further than the bottle suggests.",
  },
  "Water & Air Treatment": {
    blurb: "Certified filtration systems, tested against 170+ contaminants.",
  },
};

type CategoryVisual = {
  icon: LucideIcon;
  gradient: string;
  // Real product photo, used in place of the icon mockup wherever set.
  image?: string;
  // "transparent": photo already has a cut-out/alpha background, drop straight on the page.
  // "card": photo has an opaque (usually white) background, so it needs a light plate behind it.
  photoStyle?: "transparent" | "card";
};

export const CATEGORY_VISUAL: Record<CatalogCategory, CategoryVisual> = {
  Nutrilite: {
    icon: Pill,
    gradient: "from-emerald-500/25 to-emerald-500/0",
    image: "/Nutralite double X.jpg",
    photoStyle: "card",
  },
  Artistry: {
    icon: Sparkles,
    gradient: "from-rose-500/25 to-rose-500/0",
  },
  XS: {
    icon: Zap,
    gradient: "from-orange-500/25 to-orange-500/0",
    image: "/XS classic.jpg",
    photoStyle: "card",
  },
  "Personal Care": { icon: Droplet, gradient: "from-cyan-500/25 to-cyan-500/0" },
  "Home Care": { icon: SprayCan, gradient: "from-amber-500/25 to-amber-500/0" },
  "Water & Air Treatment": {
    icon: Wind,
    gradient: "from-blue-500/25 to-blue-500/0",
    image: "/espring under the counter.jpg",
    photoStyle: "card",
  },
};

// RGB triplets (not hex) so callers can drop them straight into an
// `rgba(${color}, alpha)` string for a radial-gradient glow. Deliberately
// separate from CATEGORY_VISUAL.gradient (a lighter Tailwind token used for
// flat fills elsewhere) since this is tuned for a deep, saturated ambient
// light look on near-black card backgrounds.
export const CATEGORY_GLOW: Record<CatalogCategory, string> = {
  Nutrilite: "16, 122, 87",
  Artistry: "128, 22, 58",
  XS: "191, 99, 20",
  "Personal Care": "13, 129, 149",
  "Home Care": "146, 96, 20",
  "Water & Air Treatment": "22, 90, 158",
};

// Placeholder stock photos until real product photography is in. Cycled
// across categories rather than one-per-category since there are only 4.
const PLACEHOLDER_PHOTOS = [
  "https://images.unsplash.com/photo-1494806812796-244fe51b774d?q=80&w=3534&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1518710843675-2540dd79065c?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1590041794748-2d8eb73a571c?q=80&w=3456&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "https://images.unsplash.com/photo-1679420437432-80cfbf88986c?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
];

export const CATEGORY_PLACEHOLDER_IMAGE: Record<CatalogCategory, string> = {
  Nutrilite: PLACEHOLDER_PHOTOS[0],
  Artistry: PLACEHOLDER_PHOTOS[1],
  XS: PLACEHOLDER_PHOTOS[2],
  "Personal Care": PLACEHOLDER_PHOTOS[3],
  "Home Care": PLACEHOLDER_PHOTOS[0],
  "Water & Air Treatment": PLACEHOLDER_PHOTOS[1],
};

// Prices/ingredients researched from amway.com listings, FDA DailyMed (Glister),
// and EPA Safer Choice records where noted. amway.com blocks automated price
// scraping, so many figures are unconfirmed: priceStatus reflects that honestly.
export const catalog: CatalogProduct[] = [
  // ---------- Nutrilite ----------
  {
    slug: "nutrilite-double-x",
    name: "Nutrilite Double X Vitamin/Mineral/Phytonutrient Supplement",
    category: "Nutrilite",
    size: "31-day supply, with 3-compartment case",
    price: "$66.00",
    priceStatus: "confirmed",
    ingredients: [
      "Vitamin A (beta-carotene): supports vision, immune function, and skin health",
      "Vitamin C (ascorbic acid): supports immune function, collagen formation, and acts as an antioxidant",
      "Vitamin D3: supports bone health and calcium absorption",
      "Vitamin E (d-alpha-tocopheryl): antioxidant that protects cells from oxidative damage",
      "Thiamine / B1: supports energy metabolism and nerve function",
      "Riboflavin / B2: supports energy production and cellular function",
      "Niacin / B3: supports energy metabolism and healthy skin",
      "Vitamin B6: supports protein metabolism and brain function",
      "Folate: supports cell division and DNA synthesis",
      "Vitamin B12: supports nerve function and red blood cell formation",
      "Biotin: supports metabolism and healthy hair, skin, and nails",
      "Pantothenic acid / B5: supports energy metabolism from food",
      "Calcium (carbonate): supports bone and teeth strength",
      "Iron (fumarate): supports oxygen transport in the blood",
      "Iodine (potassium iodide, kelp): supports thyroid hormone production",
      "Magnesium (oxide): supports muscle, nerve, and bone function",
      "Zinc (oxide): supports immune function and wound healing",
      "Selenium (sodium selenite): antioxidant that supports thyroid function",
      "Copper (gluconate): supports iron metabolism and connective tissue",
      "Manganese (sulfate): supports bone formation and antioxidant enzymes",
      "Chromium (chloride): supports normal carbohydrate and fat metabolism",
      "Molybdenum (sodium molybdate): supports amino acid metabolism enzymes",
      "22 plant concentrates (lycopene, lutein, quercetin, rosemary and turmeric extracts, and more)",
      "Phytocolor Balance berry blend (grape, black currant, elderberry, blueberry)",
      "Phytoprotect Blend (rosemary, turmeric, fava d'anta extracts)",
    ],
    description: "Flagship daily multivitamin, mineral & phytonutrient supplement: 3 tablets, twice a day.",
    hook: "The best-known product in this lineup worldwide: grown on our own certified organic farms, not sourced from an anonymous supplement factory.",
    badge: "Bestseller",
    videoId: "bKagFfxwZtw",
    madeIn: "USA",
    image: "/Nutralite double X.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-vitamin-c",
    name: "Nutrilite Vitamin C Extended Release",
    category: "Nutrilite",
    size: "60 tablets",
    price: "$20.00",
    priceStatus: "confirmed",
    ingredients: [
      "Vitamin C / ascorbic acid, 500 mg (556% DV): supports immune function, collagen formation, and acts as an antioxidant",
      "Acerola cherry powder, 120 mg: whole-food source contributing part of the vitamin C",
      "Citrus bioflavonoid complex, 35 mg: plant compound that naturally occurs alongside vitamin C in citrus",
      "Extended-release tablet matrix: releases over roughly 8 hours instead of all at once",
    ],
    description: "Slow-release vitamin C tablet for daily immune support.",
    hook: "Releases vitamin C over roughly 8 hours instead of spiking and clearing in one.",
    madeIn: "USA",
    image: "/Nutralite vitamin C.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-kids-chewable",
    name: "Nutrilite Kids Daily Chewable Multivitamins",
    category: "Nutrilite",
    size: "Chewable tablets, strawberry-orange",
    price: "$19.00",
    priceStatus: "confirmed",
    ingredients: [
      "Vitamin A: supports vision and immune function",
      "Vitamin C: supports immune function and acts as an antioxidant",
      "Vitamin D: supports bone health and calcium absorption",
      "Vitamin E: acts as an antioxidant",
      "Vitamin K: supports normal blood clotting and bone metabolism",
      "Thiamine / B1: supports energy metabolism",
      "Riboflavin / B2: supports energy production",
      "Niacin / B3: supports energy metabolism and healthy skin",
      "Vitamin B6: supports brain development and protein metabolism",
      "Folate: supports cell division and growth",
      "Vitamin B12: supports nerve function and red blood cell formation",
      "Biotin: supports metabolism and healthy hair and skin",
      "Pantothenic acid / B5: supports energy metabolism from food",
      "Calcium: supports bone and teeth development",
      "Iron: supports oxygen transport and cognitive development",
      "Iodine: supports thyroid hormone production",
      "Magnesium: supports muscle, nerve, and bone function",
      "Zinc: supports immune function and growth",
      "Nutrilite 5-Color Blend: pineapple, spinach, blueberry, passion fruit, papaya, and guava concentrates",
    ],
    description: "Chewable multivitamin formulated for children ages 4-12.",
    hook: "Tastes like fruit candy: the rare kids' vitamin nobody has to be bribed into taking.",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-omega",
    name: "Nutrilite Omega",
    category: "Nutrilite",
    size: "Softgel bottle",
    price: "$24.00",
    priceStatus: "confirmed",
    ingredients: [
      "Purified fish oil: anchovy, mackerel, sardine (Friend of the Sea certified sustainable)",
      "500+ mg combined EPA/DHA per serving",
      "White chia seed oil (ALA + natural vitamin E)",
    ],
    description: "Omega-3 fish oil softgel supplement for heart and brain health.",
    hook: "Certified sustainably wild-caught: not just a claim on the label, an actual third-party certification.",
    madeIn: "USA",
    image: "/Nutralite omega.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-advanced-omega",
    name: "Nutrilite Advanced Omega",
    category: "Nutrilite",
    size: "Softgel bottle (count not shown on front label)",
    price: "$40.00",
    priceStatus: "confirmed",
    ingredients: ["Concentrated fish oil formula, positioned above the standard Nutrilite Omega softgel"],
    description: "Higher-concentration fish oil softgel, a step up from the standard Nutrilite Omega.",
    hook: "For anyone who wants a more concentrated omega-3 dose without taking more softgels.",
    madeIn: "USA",
    image: "/Nutralite advanced omega.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-healthy-aging-solution",
    name: "Nutrilite Healthy Aging Solution",
    category: "Nutrilite",
    size: "Bundle (contents not shown on front label)",
    price: "$143.00",
    priceStatus: "confirmed",
    ingredients: ["A curated bundle of Nutrilite products built around healthy-aging support"],
    description: "A themed Nutrilite product bundle built around healthy aging.",
    hook: "A pre-built starter bundle for healthy aging, instead of piecing one together yourself.",
    madeIn: "Not publicly confirmed",
    image: "/Nutralite healthy aging solutions.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-sleep-and-stress-solution",
    name: "Nutrilite Sleep and Stress Solution",
    category: "Nutrilite",
    size: "Bundle (contents not shown on front label)",
    price: "$186.50",
    priceStatus: "confirmed",
    ingredients: ["A curated bundle of Nutrilite products built around sleep and stress support"],
    description: "A themed Nutrilite product bundle pairing sleep support with stress support.",
    hook: "Pairs sleep and stress support in one bundle instead of two separate purchases.",
    madeIn: "Not publicly confirmed",
    image: "/Nutralite sleep and stress solution.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-all-plant-protein",
    name: "Nutrilite All Plant Protein Powder",
    category: "Nutrilite",
    size: "Tri-blend powder",
    price: "Ask for current price",
    priceStatus: "on-request",
    ingredients: [
      "Soy protein isolate (~80%)",
      "Wheat protein (~10%)",
      "Pea protein (~7.5%)",
      "8 g protein per 10 g serving: all 9 essential amino acids",
    ],
    description: "Plant-based protein powder built from a three-source blend.",
    hook: "A tri-blend engineered to cover all nine essential amino acids: something most single-source plant proteins can't say.",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-organics-plant-protein",
    name: "Nutrilite Organics Plant Protein Powder",
    category: "Nutrilite",
    size: "Vanilla or chocolate",
    price: "$41.00",
    priceStatus: "confirmed",
    ingredients: ["USDA-organic-certified plant protein blend", "No added sugar"],
    description: "USDA-organic-certified plant protein powder.",
    hook: "Nutrilite's newest protein line, and the first to carry full USDA Organic certification.",
    badge: "New",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-cal-mag-d",
    name: "Nutrilite Cal Mag D",
    category: "Nutrilite",
    size: "Tablet bottle",
    price: "$43.00",
    priceStatus: "confirmed",
    ingredients: [
      "Vitamin D3, 15 mcg (75% DV) per 3-tablet daily serving: supports bone health and calcium absorption",
      "Calcium (carbonate + calcified seaweed), 600 mg (46% DV): supports bone and teeth strength",
      "Magnesium (oxide), 200 mg (47% DV): supports muscle, nerve, and bone function",
      "Zinc (sulfate), 15 mg (136% DV): supports immune function and bone growth",
      "Manganese (citrate), 3.5 mg (152% DV): supports bone formation",
    ],
    description: "Bone-health supplement combining calcium, magnesium, vitamin D, zinc, and manganese.",
    hook: "Sources its calcium from calcified seaweed instead of ground-up rock.",
    madeIn: "USA",
  },
  {
    slug: "nutrilite-cholesterol-health",
    name: "Nutrilite Cholesterol Health",
    category: "Nutrilite",
    size: "60 softgels, 2 softgels 1x a day",
    price: "$35.00",
    priceStatus: "confirmed",
    ingredients: ["Formulated to support cardiovascular health", "60 softgels per bottle, 2 softgels once a day"],
    description: "Cardiovascular-health support softgel, separate from the general multivitamin lines.",
    hook: "A dedicated cardiovascular-support softgel rather than a general multivitamin claim.",
    madeIn: "USA",
    image: "/Nutralite Cholesterol Health.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-organics-ashwagandha",
    name: "Nutrilite Organics Ashwagandha Capsules",
    category: "Nutrilite",
    size: "60 capsules",
    price: "$44.00",
    priceStatus: "confirmed",
    ingredients: [
      "USDA Organic-certified ashwagandha",
      "Non-GMO Project Verified",
      "Marketed to manage occasional stress and support sleep and balanced mood",
    ],
    description: "Organic ashwagandha capsules for stress management and sleep support.",
    hook: "USDA-organic ashwagandha aimed at stress and sleep, not general vitamins.",
    madeIn: "USA",
    image: "/Nutralite ashwagandha.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-balance-within-probiotic",
    name: "Nutrilite Balance Within Probiotic",
    category: "Nutrilite",
    size: "1 box (serving count not shown on front label)",
    price: "$43.00",
    priceStatus: "confirmed",
    ingredients: [
      "Probiotic blend delivered with Nutrilite's 'Arrive Alive' technology",
      "Marketed to support immunity and healthy digestion",
    ],
    description: "Probiotic supplement supporting immunity and healthy digestion.",
    hook: "Built around Nutrilite's own 'Arrive Alive' delivery technology, aimed at digestion and immunity together.",
    madeIn: "USA",
    image: "/Nutralite balance with probiotic.jpg",
    photoStyle: "card",
  },
  {
    slug: "n-by-nutrilite-go-shield-gummies",
    name: "Nutrilite Go Shield Immunity Gummies, Elderberry Lemon",
    category: "Nutrilite",
    size: "Gummies, elderberry lemon flavor (count not shown on front label)",
    price: "$22.00",
    priceStatus: "confirmed",
    ingredients: ["Vitamin C, zinc, and elderberry", "Elderberry lemon flavor, with other natural flavors"],
    description: "Immunity-support gummies with vitamin C, zinc, and elderberry.",
    hook: "Part of Nutrilite's 'n*' gummy sub-line for a younger, grab-and-go audience, instead of the classic tablet format.",
    madeIn: "USA",
    image: "/Nutralite immunity gummies.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-mens-pack",
    name: "Nutrilite Men's Pack",
    category: "Nutrilite",
    size: "30 packets, 1 packet a day",
    price: "$74.00",
    priceStatus: "confirmed",
    ingredients: ["Convenient daily vitamin and mineral packets formulated for men"],
    description: "Daily vitamin and mineral packets formulated for men, 30 packets per box.",
    hook: "A grab-and-go daily packet format for men who don't want to manage separate bottles.",
    madeIn: "USA",
    image: "/Nutralite mens pack.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-perfect-pack",
    name: "Nutrilite Perfect Pack",
    category: "Nutrilite",
    size: "60 packets, 2 packets a day",
    price: "$167.00",
    priceStatus: "confirmed",
    ingredients: [
      "22 vitamins and minerals with more than 22 plant concentrates",
      "Includes the Double X supplement",
    ],
    description: "Daily supplement packets built around the Double X formula, 60 packets per box.",
    hook: "Bundles the Double X supplement into a daily packet format instead of separate bottles.",
    madeIn: "USA",
    image: "/Nutralite perfect pack.jpg",
    photoStyle: "card",
  },
  {
    slug: "n-by-nutrilite-sweet-dreams-gummies",
    name: "Nutrilite Sweet Dreams Sleep Gummies, Blueberry Lavender",
    category: "Nutrilite",
    size: "Gummies, blueberry lavender flavor (count not shown on front label)",
    price: "$19.50",
    priceStatus: "confirmed",
    ingredients: ["Melatonin and passionflower", "Blueberry lavender flavor, with other natural flavors"],
    description: "Sleep-support gummies with melatonin and passionflower.",
    hook: "A melatonin-and-passionflower gummy from the same 'n*' sub-line as Go Shield, aimed at sleep instead of immunity.",
    madeIn: "USA",
    image: "/Nutralite sleep gummies.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-sleep-health",
    name: "Nutrilite Sleep Health",
    category: "Nutrilite",
    size: "30 capsules, 1 capsule at bedtime",
    price: "$29.00",
    priceStatus: "confirmed",
    ingredients: ["Plant-based melatonin"],
    description: "Sleep-support capsules built on plant-based melatonin, 30 capsules per bottle.",
    hook: "A plant-based melatonin capsule for people who'd rather take a bedtime capsule than a gummy.",
    madeIn: "USA",
    image: "/Nutralite sleep health.png",
    photoStyle: "transparent",
  },
  {
    slug: "nutrilite-twist-tubes-2go-strawberry-kiwi",
    name: "Nutrilite Twist Tubes 2GO Immunity Health, Strawberry Kiwi",
    category: "Nutrilite",
    size: "10 mL twist tubes",
    price: "$24.00",
    priceStatus: "confirmed",
    ingredients: ["Naturally flavored, strawberry kiwi", "Formulated to support the immune system"],
    description: "Liquid immunity-support supplement in single-serve 10 mL twist tubes, strawberry kiwi flavor.",
    hook: "A liquid, on-the-go immunity format instead of a tablet or gummy: twist, drink, done.",
    madeIn: "USA",
    image: "/Nutralite twisttube strawberry kiwi.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-vitamin-b-dual-action",
    name: "Nutrilite Vitamin B Dual-Action",
    category: "Nutrilite",
    size: "120 tablets, 1 tablet 1x a day",
    price: "$38.00",
    priceStatus: "confirmed",
    ingredients: ["B-vitamin complex marketed to help fight fatigue"],
    description: "B-vitamin supplement marketed to help fight fatigue, 120 tablets per bottle.",
    hook: "A dedicated B-vitamin formula for fatigue, separate from what's already in Double X.",
    madeIn: "USA",
    image: "/Nutralite vitamin B.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-wellness-bar-nutty-dark-chocolate",
    name: "Nutrilite Wellness Bar, Nutty Dark Chocolate",
    category: "Nutrilite",
    size: "12 bars, 1 lb 0.9 oz (480 g) box",
    price: "$29.00",
    priceStatus: "confirmed",
    ingredients: [
      "8 g protein per bar",
      "Gluten-free",
      "No artificial colors, flavors, preservatives, or sweeteners",
    ],
    description: "Nutty dark chocolate protein bar, 8 g protein per bar, 12 bars per box.",
    hook: "The only food-format item in the lineup: a protein bar instead of a pill, powder, or gummy.",
    madeIn: "USA",
    image: "/Nutralite wellness bar nutty chocolate.jpg",
    photoStyle: "card",
  },
  {
    slug: "nutrilite-womens-pack",
    name: "Nutrilite Women's Pack",
    category: "Nutrilite",
    size: "30 packets, 1 packet a day",
    price: "$59.00",
    priceStatus: "confirmed",
    ingredients: ["Convenient daily vitamin and mineral packets formulated for women"],
    description: "Daily vitamin and mineral packets formulated for women, 30 packets per box.",
    hook: "The women's-formulated counterpart to the Men's Pack, in the same daily-packet format.",
    madeIn: "USA",
    image: "/Nutralite womens pack.jpg",
    photoStyle: "card",
  },

  // ---------- Artistry ----------
  {
    slug: "artistry-defying-serum",
    name: "Artistry Skin Nutrition Defying Serum",
    category: "Artistry",
    size: "30 mL / 1.0 fl. oz.",
    price: "$85.00",
    priceStatus: "confirmed",
    ingredients: [
      "Willow bark extract: gently smooths rough skin texture",
      "Hydrolyzed oats: calms and soothes irritated skin",
      "Ashwagandha root extract: an herb believed to help skin look firmer over time",
      "Seaweed extract: helps skin hold onto moisture",
      "Holy basil leaf extract: has calming, antioxidant properties",
      "Sodium hyaluronate: a lightweight moisture-holding ingredient (a form of hyaluronic acid)",
      "Chia seed extract: adds nourishing fatty acids that help skin stay soft",
    ],
    description: "Anti-aging facial serum targeting fine lines, pores, and skin elasticity.",
    hook: "Built around ashwagandha and holy basil extracts: ingredients most drugstore serums have never touched.",
    videoId: "wrCgBjvd5eU",
    madeIn: "USA",
    image: "/Artistry Defying Serum.jpg",
    photoStyle: "card",
  },
  {
    slug: "artistry-hydrating-gel-cream",
    name: "Artistry Skin Nutrition Hydrating Gel Cream",
    category: "Artistry",
    size: "50 mL / 1.7 fl. oz.",
    price: "$45.00",
    priceStatus: "confirmed",
    ingredients: [
      "\"Prevent Complex\": Artistry's own blend of plant ingredients meant to help skin stay hydrated through the day",
      "Bergamot, green tea, and amber: give the cream its light scent",
    ],
    description: "Daily gel-cream moisturizer for normal-to-oily skin.",
    hook: "A gel-cream light enough for oily skin, built on a proprietary botanical blend that isn't fully published.",
    madeIn: "USA",
    image: "/Artistry Hydrating Gel Cream.jpg",
    photoStyle: "card",
  },
  {
    slug: "artistry-ideal-radiance-cc-cream",
    name: "Artistry Ideal Radiance Illuminating CC Cream",
    category: "Artistry",
    size: "30 mL / 1 fl. oz.",
    price: "Ask for current price",
    priceStatus: "on-request",
    ingredients: [
      "AA2G (a stable form of vitamin C): helps brighten skin and fade uneven tone over time",
      "SPF 50: sunscreen protection built right into the cream",
    ],
    description: "Tinted CC cream with SPF 50 that evens tone and brightens skin.",
    hook: "SPF 50 and a stabilized vitamin-C derivative in one tinted cream: most CC creams only pick one.",
    madeIn: "USA",
    image: "/Artistry Illuminating cc cream.jpg",
    photoStyle: "card",
  },
  {
    slug: "artistry-signature-eyes-mascara",
    name: "Artistry Go Vibrant Waterproof Length Serum Mascara (Black)",
    category: "Artistry",
    size: "8.3 mL / 0.28 fl. oz.",
    price: "$28.00",
    priceStatus: "confirmed",
    ingredients: ["Full ingredient list not independently published: ask for the current product insert"],
    description: "Volumizing, lengthening mascara in black.",
    hook: "Volumizing and lengthening in the same tube: no separate primer step required.",
    madeIn: "USA",
    image: "/Artistry Mascara.png",
    photoStyle: "transparent",
  },
  {
    slug: "artistry-go-vibrant-lipstick",
    name: "Artistry Go Vibrant Cream Lipstick",
    category: "Artistry",
    size: "0.13 oz",
    price: "$26.00",
    priceStatus: "confirmed",
    ingredients: [
      "Liquid-pigment color base: gives long-lasting color that feels lightweight instead of heavy or waxy",
      "Available in 10 shades",
    ],
    description: "Cream-finish lipstick available in 10 shades.",
    hook: "Uses a liquid-pigment base for color meant to feel weightless, not waxy.",
    badge: "New",
    madeIn: "USA",
    image: "/Artistry Vibrant lipstick.jpg",
    photoStyle: "card",
  },
  {
    slug: "artistry-men-balancing-hydrator",
    name: "Artistry Men Post Shave Toner",
    category: "Artistry",
    size: "150 mL",
    price: "$39.00",
    priceStatus: "confirmed",
    ingredients: [
      "Zinc PCA: helps control oil and shine through the day",
      "Witch hazel extract: a natural toner that helps tighten the look of pores",
      "Aloe leaf juice: soothes and hydrates skin",
      "Caffeine: helps de-puff and perk up tired-looking skin",
      "Sodium hyaluronate: helps skin hold onto moisture",
      "Ceramide 3: helps repair and strengthen skin's natural protective barrier",
    ],
    description: "Lightweight post-shave toner for men: soothes, tightens pores, and hydrates.",
    hook: "Built for men's skin specifically: calms razor irritation while controlling oil and shine.",
    madeIn: "USA",
  },
  {
    slug: "artistry-exact-fit-powder-foundation",
    name: "Artistry Exact Fit Powder Foundation",
    category: "Artistry",
    size: "12 g / 0.4 oz.",
    price: "Ask for current price",
    priceStatus: "on-request",
    ingredients: [
      "Talc, kaolin, and pearl powder: mineral powders that create a smooth, blurred matte finish",
      "SPF 20: built-in sun protection so you can skip a separate sunscreen step",
    ],
    description: "Pressed powder foundation with SPF 20, oil-control matte finish.",
    hook: "Pressed powder with SPF 20 built in: skips the separate sunscreen step most powders require.",
    madeIn: "USA",
    image: "/Artistry powder foundation.png",
    photoStyle: "transparent",
  },

  // ---------- Personal Care ----------
  {
    slug: "satinique-smooth-moisture-shampoo",
    name: "Satinique Smooth Moisture Shampoo",
    category: "Personal Care",
    size: "280 mL",
    price: "$15.00",
    priceStatus: "confirmed",
    ingredients: [
      "Almond oil: adds shine and softness to dry, unruly hair",
      "Sunflower seed complex water: helps lock in moisture",
    ],
    description: "Moisturizing shampoo for dry, unruly hair.",
    hook: "Built around a sunflower-seed water complex you won't find in a drugstore shampoo aisle.",
    videoId: "jB-GeJZ30EQ",
    madeIn: "USA",
    image: "/Satnique Moisture Shampoo.png",
    photoStyle: "transparent",
  },
  {
    slug: "satinique-smooth-moisture-conditioner",
    name: "Satinique Smooth Moisture Conditioner",
    category: "Personal Care",
    size: "Companion size to the Smooth Moisture Shampoo",
    price: "$15.00",
    priceStatus: "confirmed",
    ingredients: [
      "Almond oil: adds shine and softness to dry, unruly hair",
      "Sunflower seed complex water: helps lock in moisture",
    ],
    description: "Moisturizing conditioner paired with the Smooth Moisture Shampoo.",
    hook: "Formulated as one half of a pair: not a generic conditioner bottled to match anything.",
    madeIn: "USA",
    image: "/Satnique Moisture Conditioner.png",
    photoStyle: "transparent",
  },
  {
    slug: "glister-toothpaste",
    name: "Glister Multi-Action Fluoride Toothpaste",
    category: "Personal Care",
    size: "200 g",
    price: "$7.25",
    priceStatus: "confirmed",
    ingredients: [
      "Sodium fluoride 0.21%: the active ingredient that fights cavities",
      "Hydrated silica: a gentle polishing ingredient that helps remove surface stains",
      "Xylitol: a sugar substitute that also helps fight cavity-causing bacteria",
      "Sorbitol and glycerin: keep the paste smooth and moist",
    ],
    description: "Anticavity fluoride toothpaste that cleans, helps whiten, and freshens breath.",
    hook: "Its fluoride content is on file with the FDA's own public drug listing database: not just on the box.",
    videoId: "1yAZfkYcQpA",
    madeIn: "USA",
    image: "/Glister Multi action Toothpaste.jpg",
    photoStyle: "card",
  },
  {
    slug: "glister-oral-rinse",
    name: "Glister Multi-Action Concentrated Oral Rinse",
    category: "Personal Care",
    size: "59 mL concentrate (~100 rinses)",
    price: "$14.00",
    priceStatus: "confirmed",
    ingredients: [
      "Cetylpyridinium chloride: the active ingredient that kills germs and helps reduce plaque",
      "Peppermint flavor: freshens breath, alcohol-free so it won't sting or burn",
    ],
    description: "Alcohol-free concentrated oral rinse that reduces plaque and freshens breath.",
    hook: "One small concentrate bottle stretches into about 100 rinses: no alcohol burn included.",
    madeIn: "USA",
    image: "/Glister oral rinse.jpg",
    photoStyle: "card",
  },
  {
    slug: "gh-protect-deodorant-roll-on",
    name: "g&h Protect Antiperspirant Deodorant Roll-On",
    category: "Personal Care",
    size: "100 mL",
    price: "$10.75",
    priceStatus: "confirmed",
    ingredients: [
      "Nutrilite-certified green tea extract: a natural antioxidant",
      "Cica water: a calming plant extract that soothes irritated skin",
      "Rosemary extract: adds antioxidant protection",
      "Prebiotics: help support the skin's healthy bacteria",
    ],
    description: "Roll-on antiperspirant/deodorant rated for up to 48-hour protection.",
    hook: "Uses the same Nutrilite-certified green tea extract as the supplement line: not an unrelated formula slapped on a new label.",
    madeIn: "USA",
    image: "/G&H deodrant roll on.jpg",
    photoStyle: "card",
  },
  {
    slug: "gh-protect-plus-deodorant",
    name: "G&H Protect+ Long Lasting Deodorant",
    category: "Personal Care",
    size: "83.6 g stick",
    price: "$10.50",
    priceStatus: "confirmed",
    ingredients: ["Aluminum-free, alcohol-free, paraben-free, plant-based formula"],
    description: "Aluminum-free deodorant stick for daily use, rated 24-hour+ protection.",
    hook: "Skips aluminum entirely without giving up all-day odor protection.",
    madeIn: "USA",
    image: "/G&H aluminium free deodrant.jpg",
    photoStyle: "card",
  },
  {
    slug: "gh-nourish-body-wash",
    name: "g&h Nourish Body Wash",
    category: "Personal Care",
    size: "400 mL",
    price: "$14.50",
    priceStatus: "confirmed",
    ingredients: [
      "Nutrilite white chia seed oil: nourishes and softens skin",
      "Bamboo water: helps hydrate skin",
      "Olive oil: moisturizes; the formula overall is sulfate-free (no harsh foaming agents)",
    ],
    description: "Moisturizing, sulfate-free body wash for dry skin.",
    hook: "Gentle enough to double as a face wash: most body washes won't make that claim.",
    madeIn: "USA",
    image: "/G&H body wash.png",
    photoStyle: "transparent",
  },

  // ---------- XS ----------
  {
    slug: "xs-classic",
    name: "XS Energy Drink: Classic",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "confirmed",
    ingredients: [
      "114 mg caffeine per can",
      "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy",
      "Panax and American ginseng: herbal extracts traditionally used for energy and focus",
      "Sugar-free: sweetened with sucralose & acesulfame potassium",
    ],
    description: "The original XS flavor: sugar-free, 15 calories per can.",
    hook: "114 mg of caffeine and zero sugar: built to hit without the crash that follows a sugary energy drink.",
    badge: "Bestseller",
    videoId: "MI0n6j8yCak",
    madeIn: "USA",
    image: "/XS classic.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-tropical",
    name: "XS Energy Drink: Tropical",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "confirmed",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Tropical fruit flavored energy drink, sugar-free, 15 calories per can.",
    hook: "Same energy formula as Classic, in a tropical-fruit flavor for people who find Classic too plain.",
    madeIn: "USA",
    image: "/XS tropical.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-black-cherry-cola",
    name: "XS Energy Drink: Black Cherry Cola",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "confirmed",
    ingredients: ["114 mg caffeine per can", "Cherry juice concentrate", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy"],
    description: "Cherry-cola flavored energy drink, sugar-free, 15 calories per can.",
    hook: "Tastes like a cherry cola float: real cherry juice concentrate does the flavor work.",
    madeIn: "USA",
    image: "/XS black cherry.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-citrus",
    name: "XS Energy Drink: Citrus",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "approx",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Citrus flavored energy drink, sugar-free, 15 calories per can.",
    hook: "A brighter, orange-citrus take on the classic formula for people who find Classic too plain.",
    madeIn: "USA",
    image: "/XS citrus.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-electric-lemon",
    name: "XS Energy Drink: Electric Lemon",
    category: "XS",
    size: "12 fl oz can",
    price: "$35.00",
    priceStatus: "confirmed",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Limited-edition lemon flavored energy drink, sugar-free, sold in its own cartoon-mascot can art.",
    hook: "Same core formula as Classic, in a limited-edition lemon flavor and can design.",
    madeIn: "USA",
    image: "/XS electric lemon.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-naranja",
    name: "XS Energy Drink: Naranja",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "approx",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Orange (naranja) flavored energy drink, sugar-free, 15 calories per can.",
    hook: "XS's orange flavor, labeled naranja on the can rather than translated to English.",
    madeIn: "USA",
    image: "/XS naranja.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-root-beer",
    name: "XS Energy Drink: Root Beer",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "approx",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Root beer flavored energy drink, sugar-free, 15 calories per can.",
    hook: "A root-beer-float flavor most energy drink brands don't bother making.",
    madeIn: "USA",
    image: "/XS root beer.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-summit",
    name: "XS Energy Drink: Summit",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "approx",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Summit flavored energy drink, sugar-free, 15 calories per can.",
    hook: "One of the less common XS flavors, sold under its own name rather than a fruit descriptor.",
    madeIn: "USA",
    image: "/XS summit.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-tamarindo",
    name: "XS Energy Drink: Tamarindo",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "approx",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Tamarindo (tamarind) flavored energy drink, sugar-free, 15 calories per can.",
    hook: "A tamarind flavor aimed at the same audience as Naranja: uncommon in mainstream energy drinks.",
    madeIn: "USA",
    image: "/XS tamrindo.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-watermelon-lemonade",
    name: "XS Energy Drink: Watermelon Lemonade",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "approx",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Watermelon lemonade flavored energy drink, sugar-free, 15 calories per can.",
    hook: "Watermelon and lemonade in one can, sweeter and more citrus-forward than the fruit-only flavors.",
    madeIn: "USA",
    image: "/XS watermelon.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-wild-berry",
    name: "XS Energy Drink: Wild Berry",
    category: "XS",
    size: "12 fl oz can, case of 12",
    price: "$37.00",
    priceStatus: "approx",
    ingredients: ["114 mg caffeine per can", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy", "Ginseng: an herbal extract traditionally used for energy and focus"],
    description: "Wild berry flavored energy drink, sugar-free, 15 calories per can.",
    hook: "A mixed-berry flavor, one of the more universally-liked options in the lineup.",
    madeIn: "USA",
    image: "/XS wild berry.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-sparkling-mango-pineapple-guava",
    name: "XS Sparkling Juiced Energy: Mango Pineapple Guava",
    category: "XS",
    size: "12 fl oz can",
    price: "$35.00",
    priceStatus: "confirmed",
    ingredients: [
      "25% real fruit juice from concentrate",
      "~11 g sugar (naturally from juice, none added)",
      "280% DV vitamin C",
      "114 mg caffeine",
    ],
    description: "Juice-based sparkling energy drink made with real fruit juice, mango-pineapple-guava flavor.",
    hook: "280% of a day's vitamin C in one can, from a real-juice blend: most energy drinks skip that entirely.",
    madeIn: "USA",
    image: "/XS sparkling mango pineapple guava.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-sparkling-pink-grapefruit",
    name: "XS Sparkling Juiced Energy: Pink Grapefruit",
    category: "XS",
    size: "12 fl oz can",
    price: "$35.00",
    priceStatus: "confirmed",
    ingredients: [
      "25% real fruit juice from concentrate",
      "~11 g sugar (naturally from juice, none added)",
      "280% DV vitamin C",
      "114 mg caffeine",
    ],
    description: "Juice-based sparkling energy drink made with real fruit juice, pink grapefruit flavor.",
    hook: "The tartest option in the Sparkling Juiced Energy line, built on the same real-juice, high-vitamin-C formula as the rest of it.",
    madeIn: "USA",
    image: "/XS sparkling pink grapefruit.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-energy-burn-kiwi-strawberry",
    name: "XS Energy + Burn: Kiwi Strawberry",
    category: "XS",
    size: "12 fl oz can",
    price: "$42.00",
    priceStatus: "confirmed",
    ingredients: [
      "Green tea extract (~50 mg EGCG per can)",
      "114 mg caffeine",
      "Chromium, ginger root extract",
    ],
    description: "Metabolism-support energy drink line built around green tea extract.",
    hook: "Adds 50 mg of EGCG from green tea on top of the usual energy blend: a metabolism angle most energy drinks skip.",
    badge: "New",
    madeIn: "USA",
    image: "/XS burn kiwi strawberry.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-burn-blue-razz",
    name: "XS Energy + Burn: Blue Razz",
    category: "XS",
    size: "12 fl oz can",
    price: "$42.00",
    priceStatus: "approx",
    ingredients: [
      "Green tea extract (~50 mg EGCG per can)",
      "114 mg caffeine",
      "Chromium, ginger root extract",
    ],
    description: "Metabolism-support energy drink line built around green tea extract, blue raspberry flavor.",
    hook: "Same EGCG-and-caffeine metabolism angle as Kiwi Strawberry, in a blue raspberry flavor.",
    madeIn: "USA",
    image: "/XS burn blue razz.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-elite-peach-mango",
    name: "XS Elite Focus: Peach Mango",
    category: "XS",
    size: "12 fl oz can",
    price: "$44.00",
    priceStatus: "confirmed",
    // Read directly off the can label; no independent listing found to confirm exact figures.
    ingredients: [
      "Natural caffeine",
      "Rhodiola: an adaptogen often used for focus and stress resilience",
      "Sweetened with stevia, not sucralose",
    ],
    description: "Focus-oriented energy drink from the XS Elite line, peach mango flavor.",
    hook: "Built around rhodiola and natural caffeine for a focus angle, sweetened with stevia instead of the sucralose blend the rest of the lineup uses.",
    badge: "New",
    madeIn: "USA",
    image: "/XS elite peach mango.jpg",
    photoStyle: "card",
  },
  {
    slug: "xs-cranberry-grape",
    name: "XS Energy Drink: Cranberry-Grape",
    category: "XS",
    size: "12 fl oz can, case of 12 (caffeine-free version also available)",
    price: "$37.00",
    priceStatus: "confirmed",
    ingredients: ["114 mg caffeine per can", "Cranberry juice concentrate", "Taurine and L-glutamine: amino acids commonly used in energy drinks to support alertness", "B-vitamins: help convert food into usable energy"],
    description: "Cranberry-grape flavored energy drink, sugar-free, 15 calories per can.",
    hook: "The only flavor in the lineup that also comes in a caffeine-free version.",
    madeIn: "USA",
    image: "/XS cranberry.jpg",
    photoStyle: "card",
  },

  // ---------- Home Care ----------
  {
    slug: "reusable-spray-bottle",
    name: "Refillable Trigger Spray Bottle",
    category: "Home Care",
    size: "500 mL empty bottle, with 1/1-9/1 dilution markings",
    price: "$6.50",
    priceStatus: "confirmed",
    ingredients: [
      "Empty, reusable pistol-grip spray bottle",
      "Printed dilution-ratio markings (1/1, 2/1, 3/1, 9/1) for mixing concentrate to water",
    ],
    description: "The reusable spray bottle the concentrated Home Care cleaners are diluted into.",
    hook: "The other half of every concentrate bottle: measured fill lines built in, so you're not eyeballing the dilution.",
    madeIn: "Not publicly confirmed",
    image: "/Spray bottle.jpg",
    photoStyle: "card",
  },
  {
    slug: "dish-drops",
    name: "Dish Drops Dishwashing Liquid",
    category: "Home Care",
    size: "1 L concentrate",
    price: "$7.75",
    priceStatus: "confirmed",
    ingredients: [
      "Aloe vera and shiso extract: plant ingredients that help keep hands from drying out while you wash dishes",
      "Biodegradable, no phosphates or chlorine",
    ],
    description: "Concentrated dishwashing liquid with aloe vera and shiso extract.",
    hook: "Rated to clean over 330 sinks full of dishes from a single bottle.",
    madeIn: "USA",
    image: "/Dishwashing liquid.jpg",
    photoStyle: "card",
  },
  {
    slug: "dish-drops-pump-bottle",
    name: "Dish Drops Dishwashing Liquid, Ready-to-Use Pump Bottle",
    category: "Home Care",
    size: "500 mL pump bottle",
    price: "Ask for current price",
    priceStatus: "on-request",
    ingredients: [
      "Same aloe vera and shiso extract formula as the 1 L concentrate",
      "Ready-to-use pump dispenser: no diluting or refilling required",
    ],
    description: "Ready-to-use pump-bottle format of Dish Drops Dishwashing Liquid.",
    hook: "Same formula as the concentrate, just in a pump bottle for whoever doesn't want to dilute their own.",
    madeIn: "USA",
    image: "/Dispenser bottle.jpg",
    photoStyle: "card",
  },
  {
    slug: "kitchen-cleaner",
    name: "Kitchen Cleaner",
    category: "Home Care",
    size: "1 L refill",
    price: "$17.00",
    priceStatus: "confirmed",
    ingredients: [
      "EPA Safer Choice recognized",
      "Independently rated SkinSAFE 91% free of common allergens",
      "Talc-free, paraben-free",
    ],
    description: "Concentrated kitchen surface cleaner and degreaser.",
    hook: "Independently rated 91% free of the most common allergens: verified by a third party, not just a label claim.",
    madeIn: "USA",
    image: "/Kitchen cleaner.jpg",
    photoStyle: "card",
  },
  {
    slug: "bathroom-cleaner",
    name: "Bathroom Cleaner",
    category: "Home Care",
    size: "1 L concentrate: refills a 500 mL spray bottle up to 8 times",
    price: "$17.00",
    priceStatus: "confirmed",
    ingredients: [
      "Citric acid: a natural ingredient that dissolves soap scum and hard-water buildup",
      "Biodegradable, no phosphates or chlorine",
    ],
    description: "Concentrated bathroom cleaner for soap scum and hard-water deposits.",
    hook: "Uses citric acid to dissolve hard-water scale instead of harsher acids under your sink.",
    madeIn: "USA",
    image: "/Bathroom cleaner.jpg",
    photoStyle: "card",
  },
  {
    slug: "all-fabric-bleach",
    name: "All Fabric Bleach",
    category: "Home Care",
    size: "1 kg (2.2 lbs), 33 loads",
    price: "$17.50",
    priceStatus: "confirmed",
    ingredients: [
      "Ultra-concentrated, color-safe bleach formula",
      "Whitens whites without the color-fading risk of chlorine bleach",
    ],
    description: "Concentrated all-fabric bleach, safe for whites and colors alike.",
    hook: "One box concentrated enough to cover 33 loads of laundry.",
    madeIn: "USA",
    image: "/All fabric bleach.jpg",
    photoStyle: "card",
  },
  {
    slug: "automatic-dish-tablets",
    name: "Automatic Dishwasher Tablets",
    category: "Home Care",
    size: "Tablet pack (count not shown on front label)",
    price: "$26.00",
    priceStatus: "confirmed",
    ingredients: [
      "Pre-measured tablet: no scooping or measuring powder or gel",
      "Formulated to cut through baked-on grease and food residue",
    ],
    description: "Pre-measured automatic dishwasher detergent tablets.",
    hook: "No scooping, no guessing: one tablet per load.",
    madeIn: "USA",
    image: "/Automatic dish tablets.jpg",
    photoStyle: "card",
  },
  {
    slug: "pursue-disinfectant-cleaner",
    name: "Pursue Disinfectant Cleaner",
    category: "Home Care",
    size: "1 qt. 2 fl. oz. (1 L)",
    price: "Ask for current price",
    priceStatus: "on-request",
    ingredients: [
      "One-step EPA-registered disinfectant, cleaner, and deodorizer",
      "Quaternary ammonium chloride blend (four active compounds)",
      "Labeled for home, hospital, institutional, and industrial use",
    ],
    description: "EPA-registered one-step disinfectant cleaner from the institutional-grade Pursue line.",
    hook: "The same one-step disinfectant labeled for hospital and food-service use, not just a household 'antibacterial' claim.",
    madeIn: "USA",
    image: "/Disinfectent cleaner.jpg",
    photoStyle: "card",
  },
  {
    slug: "disinfecting-deodorizing-spray",
    name: "Disinfecting Deodorizing Spray",
    category: "Home Care",
    size: "Aerosol (size not shown on front label)",
    price: "Ask for current price",
    priceStatus: "on-request",
    ingredients: [
      "Aerosol disinfectant and odor-eliminating spray",
      "Kills common household germs and bacteria",
      "Neutralizes odors rather than masking them with fragrance",
    ],
    description: "Aerosol disinfectant spray that also targets household odors.",
    hook: "Handles the germs and the smell in one can instead of two separate products.",
    madeIn: "USA",
    image: "/Disinfectent deo spray.jpg",
    photoStyle: "card",
  },
  {
    slug: "fabric-softener",
    name: "Fabric Softener",
    category: "Home Care",
    size: "Concentrate (size not shown on front label)",
    price: "$14.00",
    priceStatus: "confirmed",
    ingredients: [
      "Concentrated liquid fabric softener",
      "Reduces static and stiffness out of the dryer",
      "Formulated to be gentle on colorfast fabrics",
    ],
    description: "Concentrated liquid fabric softener for softer, static-free laundry.",
    hook: "Concentrated enough that a capful goes further than a typical drugstore softener.",
    madeIn: "USA",
    image: "/Fabric softner.jpg",
    photoStyle: "card",
  },
  {
    slug: "scouring-pads",
    name: "Scouring Pads",
    category: "Home Care",
    size: "Multi-pack (count not shown on front label)",
    price: "$7.00",
    priceStatus: "confirmed",
    ingredients: [
      "Non-scratch scouring pad",
      "Built for stuck-on messes without damaging most cookware finishes",
    ],
    description: "Durable non-scratch scouring pads for tough kitchen and household messes.",
    hook: "Tough enough for stuck-on messes without scratching most cookware.",
    madeIn: "USA",
    image: "/Scrub pads.jpg",
    photoStyle: "card",
  },

  // ---------- Water & Air Treatment ----------
  {
    slug: "espring-under-counter",
    name: "eSpring Under the Counter Water Treatment System",
    category: "Water & Air Treatment",
    size: "Under-counter install, single-line output",
    price: "$1,299.00",
    priceStatus: "confirmed",
    ingredients: [
      "Carbon block filter: traps contaminants and improves the taste and smell of your water",
      "UV-C light stage: kills bacteria and viruses without adding chemicals",
      "Reduces 170+ contaminants, including \"forever chemicals\" (PFOA/PFOS) and microplastics down to 0.2 microns",
      "Leaves in the beneficial minerals (calcium, magnesium) your water naturally has",
    ],
    description: "Full under-counter home water treatment and purification system.",
    hook: "Filters down to 0.2 microns while leaving the beneficial minerals in your water untouched.",
    badge: "Bestseller",
    videoId: "p5hZ4YAAU9M",
    madeIn: "USA",
    image: "/espring under the counter.jpg",
    photoStyle: "card",
  },
  {
    slug: "espring-e3-filter",
    name: "eSpring e3 Carbon Filter (replacement)",
    category: "Water & Air Treatment",
    size: "1 cartridge: rated ~1 year / 1,320 gallons",
    price: "$254.00",
    priceStatus: "confirmed",
    ingredients: [
      "Pre-filter layer: catches larger particles like sediment and rust",
      "Membrane layer: blocks smaller contaminants like lead and microplastics",
      "Carbon layer: removes chlorine taste and smell",
    ],
    description: "Annual replacement filter cartridge for current-generation eSpring systems.",
    hook: "One cartridge is rated for a full year or 1,320 gallons: whichever comes first.",
    madeIn: "USA",
    image: "/espring carbon filter.jpg",
    photoStyle: "card",
  },
  {
    slug: "atmosphere-sky",
    name: "Atmosphere Sky Air Treatment System",
    category: "Water & Air Treatment",
    size: "Whole-room unit, WiFi/app enabled",
    price: "$1,710.00",
    priceStatus: "confirmed",
    ingredients: [
      "Washable pre-filter: catches larger particles like dust and pet hair, rinse and reuse it",
      "HEPA filter: traps fine particles like pollen and smoke",
      "Carbon filter: absorbs household odors",
      "AHAM CADR certified at 300+ cfm: performance independently verified for smoke, dust, and pollen",
      "Certified allergy-friendly by ECARF and carries the Allergy UK Seal of Approval",
      "ENERGY STAR certified for low power draw",
      "Removes 340+ airborne contaminants with efficiency up to 99.99%, per the manufacturer",
      "Covers rooms up to ~465 sq ft (the AHAM-certified figure, not a 2-air-change marketing number)",
      "5-year warranty",
    ],
    description: "Smart whole-room air purifier system with app control.",
    hook: "Four independent certifications behind it: AHAM, ECARF, Allergy UK, and ENERGY STAR: the performance is audited, not just printed on the box.",
    videoId: "4kPqoatVQAc",
    badge: "New",
    madeIn: "USA",
    image: "/Atmosphere air treatment system.jpg",
    photoStyle: "card",
  },
  {
    slug: "atmosphere-sky-hepa-filter",
    name: "Atmosphere Sky Replacement HEPA Filter",
    category: "Water & Air Treatment",
    size: "1 filter: rated 1-3 years",
    price: "$192.00",
    priceStatus: "confirmed",
    ingredients: ["HEPA filtration stage", "Removes airborne allergens, bacteria, mold, and viruses (manufacturer claim)"],
    description: "Replacement HEPA filter stage for the Atmosphere Sky system.",
    hook: "A single filter stage rated to last up to three years, depending on your air quality.",
    madeIn: "USA",
    image: "/Atmosphere sky replacement HEPA filter.jpg",
    photoStyle: "card",
  },
  {
    slug: "atmosphere-sky-carbon-filter",
    name: "Atmosphere Sky Replacement Carbon (Odor) Filter",
    category: "Water & Air Treatment",
    size: "1 filter: rated 4-12 months",
    price: "$140.00",
    priceStatus: "confirmed",
    ingredients: ["Activated carbon filtration stage", "Targets household odors and gaseous contaminants"],
    description: "Replacement odor/carbon filter stage for the Atmosphere Sky system.",
    hook: "The stage that handles smell, not particles: swapped far more often than the HEPA filter.",
    madeIn: "USA",
    image: "/Atmosphere sky replacement carbon odor filter.jpg",
    photoStyle: "card",
  },
];
